### ISSUE TITLE
Saving a node again issues a bad version error

### ISSUE THREAD

**Issue by sheinbergon** [elkozmon/zoonavigator#23] opened 2018-08-28 11:15 UTC
Trying to save a node again after it has already been saved issue a bad version warning. It should either be masked or disabled instead, or the version should be fetched/updated in the UI after a save event.

Also, once such error has occurred, the user can no longer save a document until the browser/page is refreshed in its entirety.

**Comment by elkozmon** [comment] 2018-08-28 11:27
Hi!

What version of ZooNavigator are you using please?

**Comment by sheinbergon** [comment] 2018-08-28 11:34
latest

**Comment by elkozmon** [comment] 2018-08-28 11:53
Ok, well if you meant docker builds with "latest" tag I don't recommend
using them as these are development builds from master branch and instead
use fixed version tags such as 0.5.0.

The way it currently works (or should work) is just as you described, new
version is fetched after the save event and form submission is disabled
until further changes are made. Similar issue was fixed in version 0.5.0
where keyboard shortcut for submitting the form was not disabled and would
lead to the error you described if you managed to submit the form more than
once in rapid succession, hence I asked for the version you are using.

Anyways I will give it another look. Btw if you have any more info on how I
can reproduce this it would be very helpful. Thanks :)

**Comment by sheinbergon** [comment] 2018-08-28 12:47
Hi. we're using 0.5.0.
I've encountered the issues several time when, as described in main the issue.
It should server as an mre

**Comment by sheinbergon** [comment] 2018-08-28 14:32
@elkozmon it happens when saving/editing a newly created znode

**Comment by elkozmon** [comment] 2019-01-24 09:41
Hi. I just released a new version 0.6.0 in which the editor component has been reworked from the ground up so there is a good chance this issue could be gone.

**Comment by elkozmon** [comment] 2020-02-02 13:41
This seems to be fixed now.

**Closed by elkozmon** 2020-02-02 13:41 UTC
Labels: bug
