### ISSUE TITLE
Saving a node and trying to navigate outside of it still warns about "Discard changes" 

### ISSUE THREAD

**Issue by sheinbergon** [elkozmon/zoonavigator#22] opened 2018-08-28 11:12 UTC
After saving the node via the UI text editor clicking on the "home" icon or somewhere else in the node tree issues a warning about discarding unsaved values.

**Comment by elkozmon** [comment] 2020-02-02 13:41
This seems to be fixed now.

**Comment by Redirts** [comment] 2020-02-03 16:56
No, it is not fixed.

![2020-02-03_16-55-04](https://user-images.githubusercontent.com/23477559/73673159-13449a80-46a6-11ea-91f2-2e6601b3cfda.gif)

**Comment by elkozmon** [comment] 2020-02-03 17:17
@Redirts 
Sorry, I failed to mention that I was talking about the latest builds (as in `:latest` Docker image) since commit bd31f1fb1ca07bd1a7d4c206d323c0eca3cb62d5. There is no stable release of those changes yet. 

Which version were you using, please? You can figure that out by opening the menu in the top right corner and clicking Show session info. Thank you!

**Comment by Redirts** [comment] 2020-02-03 17:34
ZooNavigator version: latest-83c7683fe661

**Comment by elkozmon** [comment] 2020-02-03 17:42
Ok so that is an older release. If you pull the new image now it should work fine, I hope :)

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by elkozmon** [comment] 2020-02-03 18:49
Turns out you're right, it's still an issue. I couldn't reproduce it locally on my computer for some reason. Anyway, I'm reopening this then. Sorry.

**Closed** 2020-02-03 22:38 UTC
Labels: bug

**Comment by Redirts** [comment] 2020-02-04 10:55
Seems ok now but will let you know if it breaks in another use case. Thanks

**Comment by elkozmon** [comment] 2020-02-04 10:59
@Redirts Happy to hear that. Sure, let me know. Thank you
